/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiConsoleMetricsRouteImport } from './routes/api/console/metrics'
import { Route as ApiAdminIngestRouteImport } from './routes/api/admin/ingest'
import { Route as ApiPaymentsPaypalSubscribeRouteImport } from './routes/api/payments/paypal-subscribe'
import { Route as ApiPaymentsPaypalWebhookRouteImport } from './routes/api/payments/paypal-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleMetricsRoute = ApiConsoleMetricsRouteImport.update({
  id: '/api/console/metrics',
  path: '/api/console/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestRoute = ApiAdminIngestRouteImport.update({
  id: '/api/admin/ingest',
  path: '/api/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsPaypalSubscribeRoute =
  ApiPaymentsPaypalSubscribeRouteImport.update({
    id: '/api/payments/paypal-subscribe',
    path: '/api/payments/paypal-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaypalWebhookRoute =
  ApiPaymentsPaypalWebhookRouteImport.update({
    id: '/api/payments/paypal-webhook',
    path: '/api/payments/paypal-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/admin/upload': typeof AdminUploadRoute
  '/console': typeof ConsoleIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/console/metrics': typeof ApiConsoleMetricsRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/payments/paypal-subscribe': typeof ApiPaymentsPaypalSubscribeRoute
  '/api/payments/paypal-webhook': typeof ApiPaymentsPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/admin/upload': typeof AdminUploadRoute
  '/console': typeof ConsoleIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/console/metrics': typeof ApiConsoleMetricsRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/payments/paypal-subscribe': typeof ApiPaymentsPaypalSubscribeRoute
  '/api/payments/paypal-webhook': typeof ApiPaymentsPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/admin/upload': typeof AdminUploadRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/console/metrics': typeof ApiConsoleMetricsRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/payments/paypal-subscribe': typeof ApiPaymentsPaypalSubscribeRoute
  '/api/payments/paypal-webhook': typeof ApiPaymentsPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/upgrade'
    | '/vault'
    | '/admin/upload'
    | '/console'
    | '/api/chat'
    | '/api/console/metrics'
    | '/api/admin/ingest'
    | '/api/payments/paypal-subscribe'
    | '/api/payments/paypal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/upgrade'
    | '/vault'
    | '/admin/upload'
    | '/console'
    | '/api/chat'
    | '/api/console/metrics'
    | '/api/admin/ingest'
    | '/api/payments/paypal-subscribe'
    | '/api/payments/paypal-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/upgrade'
    | '/vault'
    | '/admin/upload'
    | '/console/'
    | '/api/chat'
    | '/api/console/metrics'
    | '/api/admin/ingest'
    | '/api/payments/paypal-subscribe'
    | '/api/payments/paypal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  UpgradeRoute: typeof UpgradeRoute
  VaultRoute: typeof VaultRoute
  AdminUploadRoute: typeof AdminUploadRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConsoleMetricsRoute: typeof ApiConsoleMetricsRoute
  ApiAdminIngestRoute: typeof ApiAdminIngestRoute
  ApiPaymentsPaypalSubscribeRoute: typeof ApiPaymentsPaypalSubscribeRoute
  ApiPaymentsPaypalWebhookRoute: typeof ApiPaymentsPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console/'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/metrics': {
      id: '/api/console/metrics'
      path: '/api/console/metrics'
      fullPath: '/api/console/metrics'
      preLoaderRoute: typeof ApiConsoleMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingest': {
      id: '/api/admin/ingest'
      path: '/api/admin/ingest'
      fullPath: '/api/admin/ingest'
      preLoaderRoute: typeof ApiAdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/paypal-subscribe': {
      id: '/api/payments/paypal-subscribe'
      path: '/api/payments/paypal-subscribe'
      fullPath: '/api/payments/paypal-subscribe'
      preLoaderRoute: typeof ApiPaymentsPaypalSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/paypal-webhook': {
      id: '/api/payments/paypal-webhook'
      path: '/api/payments/paypal-webhook'
      fullPath: '/api/payments/paypal-webhook'
      preLoaderRoute: typeof ApiPaymentsPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  UpgradeRoute: UpgradeRoute,
  VaultRoute: VaultRoute,
  AdminUploadRoute: AdminUploadRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConsoleMetricsRoute: ApiConsoleMetricsRoute,
  ApiAdminIngestRoute: ApiAdminIngestRoute,
  ApiPaymentsPaypalSubscribeRoute: ApiPaymentsPaypalSubscribeRoute,
  ApiPaymentsPaypalWebhookRoute: ApiPaymentsPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
